"use strict";
exports.__esModule = true;
var Teacher_1 = require("./models/Teacher");
var Student_1 = require("./models/Student");
var StudentService_1 = require("./services/StudentService");
var TeacherService_1 = require("./services/TeacherService");
var stsrvc = new StudentService_1["default"]();
var tcsrvc = new TeacherService_1["default"]();
var t1 = new Teacher_1["default"]('Ramlal', 21);
var t2 = new Teacher_1["default"]('Shyamlal', 33);
var s1 = new Student_1["default"]('raghav', 11, ['social', 'nepali']);
var s2 = new Student_1["default"]('mike', 13, ['computer', 'english']);
stsrvc.add(s1);
stsrvc.add(s2);
tcsrvc.add(t1);
tcsrvc.add(t2);
stsrvc.grade(s1, 'A+');
tcsrvc.teach(t1, 'nepali');
console.log('Students => ', stsrvc.getAll());
console.log('Teachers => ', tcsrvc.getAll());
